package org.jkiss.dbeaver.teststudio.core;

import com.google.gson.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.*;
import java.util.*;
import org.eclipse.core.resources.*;
import org.eclipse.core.runtime.NullProgressMonitor;

final class RunEvidenceStore {
   static final long MAX_RUN_BYTES=50L*1024*1024,MAX_ATTACHMENT_BYTES=10L*1024*1024;
   private static final String ROOT="Test Studio",RUNS="Runs";
   RunEvidenceStore(){recoverAborted();}
   JsonObject start(String project,String runId,JsonObject plan,JsonObject variables){IFolder run=run(project,runId,true);JsonObject manifest=new JsonObject();manifest.addProperty("run_id",runId);manifest.addProperty("plan_id",StudioJson.string(plan,"id",""));manifest.addProperty("state","running");manifest.addProperty("started_at",StudioJson.now());manifest.addProperty("pinned",false);write(run.getFile("manifest.json"),manifest);write(run.getFile("plan.snapshot.json"),plan);write(run.getFile("variables.masked.json"),variables);return manifest;}
   void step(String project,String runId,int index,String id,JsonObject payload){IFolder steps=child(run(project,runId,true),"steps",true);String safe=(id==null||id.isBlank()?"step":id).replaceAll("[^A-Za-z0-9._-]","_");write(steps.getFile(String.format("%03d-%s.json",index,safe)),payload);checkQuota(run(project,runId,false));}
   JsonObject attach(String project,String runId,String name,byte[] bytes){if(bytes.length>MAX_ATTACHMENT_BYTES)throw new IllegalArgumentException("Attachment exceeds 10 MiB");IFolder attachments=child(run(project,runId,true),"attachments",true);String safe=name.replaceAll("[^A-Za-z0-9._-]","_");IFile file=attachments.getFile(safe);writeBytes(file,bytes);JsonObject result=new JsonObject();result.addProperty("name",safe);result.addProperty("bytes",bytes.length);result.addProperty("sha256",sha(bytes));checkQuota(run(project,runId,false));return result;}
   JsonObject finish(String project,String runId,JsonObject report,String state,JsonObject cleanup){IFolder run=run(project,runId,false);write(run.getFile("report.json"),report);write(run.getFile("cleanup.json"),cleanup);JsonObject manifest=read(run.getFile("manifest.json"));manifest.addProperty("state",state);manifest.addProperty("finished_at",StudioJson.now());manifest.addProperty("passed",StudioJson.bool(report,"passed",false));write(run.getFile("manifest.json"),manifest);return manifest;}
   JsonObject list(String project,int limit){IFolder folder=runs(project,false);JsonArray items=new JsonArray();if(folder!=null&&folder.exists())try{Arrays.stream(folder.members()).filter(r->r instanceof IFolder).sorted(Comparator.comparingLong(IResource::getLocalTimeStamp).reversed()).limit(limit).forEach(r->{try{JsonObject m=read(((IFolder)r).getFile("manifest.json"));m.addProperty("bytes",folderSize((IFolder)r));items.add(m);}catch(Exception e){}});}catch(Exception ignored){}JsonObject result=new JsonObject();result.addProperty("count",items.size());result.add("runs",items);return result;}
   JsonObject get(String project,String runId){IFolder run=run(project,runId,false);if(run==null||!run.exists())throw new IllegalArgumentException("Run not found: "+runId);JsonObject result=new JsonObject();result.add("manifest",read(run.getFile("manifest.json")));if(run.getFile("report.json").exists())result.add("report",read(run.getFile("report.json")));if(run.getFile("cleanup.json").exists())result.add("cleanup",read(run.getFile("cleanup.json")));JsonArray steps=new JsonArray();IFolder folder=run.getFolder("steps");if(folder.exists())try{Arrays.stream(folder.members()).filter(r->r instanceof IFile).sorted(Comparator.comparing(IResource::getName)).forEach(r->steps.add(read((IFile)r)));}catch(Exception ignored){}result.add("steps",steps);result.addProperty("bytes",folderSize(run));return result;}
   JsonObject getPlan(String project,String runId){IFolder folder=run(project,runId,false);if(folder==null||!folder.exists())throw new IllegalArgumentException("Run not found: "+runId);IFile file=folder.getFile("plan.snapshot.json");if(!file.exists())throw new IllegalArgumentException("Run plan snapshot not found: "+runId);return read(file);}
   JsonObject delete(String project,String runId){IFolder run=run(project,runId,false);if(run==null||!run.exists())throw new IllegalArgumentException("Run not found: "+runId);try{run.delete(true,new NullProgressMonitor());}catch(Exception e){throw new IllegalStateException(e);}JsonObject result=new JsonObject();result.addProperty("deleted",true);result.addProperty("run_id",runId);return result;}
   JsonObject pin(String project,String runId,boolean pinned){IFolder run=run(project,runId,false);JsonObject manifest=read(run.getFile("manifest.json"));manifest.addProperty("pinned",pinned);write(run.getFile("manifest.json"),manifest);return manifest;}
   JsonObject cleanup(String project,int keepLast,int olderThanDays){IFolder folder=runs(project,false);if(folder==null||!folder.exists())return count(0);List<IFolder> candidates=new ArrayList<>();try{for(IResource r:folder.members())if(r instanceof IFolder f)candidates.add(f);}catch(Exception ignored){}candidates.sort(Comparator.comparingLong(IResource::getLocalTimeStamp).reversed());Instant cutoff=Instant.now().minus(Duration.ofDays(olderThanDays));int removed=0;for(int i=0;i<candidates.size();i++){IFolder f=candidates.get(i);JsonObject m=read(f.getFile("manifest.json"));if(StudioJson.bool(m,"pinned",false)||i<keepLast)continue;String at=StudioJson.string(m,"finished_at",StudioJson.string(m,"started_at",Instant.EPOCH.toString()));if(Instant.parse(at).isBefore(cutoff))try{f.delete(true,new NullProgressMonitor());removed++;}catch(Exception ignored){}}return count(removed);}
   JsonObject writeReport(String project,String runId,String format,String extension,byte[] bytes,boolean overwrite){IFolder reports=child(run(project,runId,false),"reports",true);IFile file=reports.getFile("report."+extension);if(file.exists()&&!overwrite)throw new IllegalArgumentException("Report exists; pass overwrite=true");writeBytes(file,bytes);JsonObject r=new JsonObject();r.addProperty("format",format);r.addProperty("path",file.getProjectRelativePath().toString());r.addProperty("bytes",bytes.length);r.addProperty("sha256",sha(bytes));return r;}
   JsonObject listReports(String project,String runId){IFolder reports=run(project,runId,false).getFolder("reports");JsonArray items=new JsonArray();if(reports.exists())try{for(IResource r:reports.members())if(r instanceof IFile f){JsonObject i=new JsonObject();i.addProperty("name",f.getName());i.addProperty("path",f.getProjectRelativePath().toString());i.addProperty("bytes",f.getLocation().toFile().length());items.add(i);}}catch(Exception ignored){}JsonObject result=new JsonObject();result.addProperty("count",items.size());result.add("reports",items);return result;}
   String readReport(String project,String runId,String name){IFile f=run(project,runId,false).getFolder("reports").getFile(name);if(!f.exists())throw new IllegalArgumentException("Report not found: "+name);try(var in=f.getContents()){byte[] bytes=in.readNBytes(1024*1024+1);if(bytes.length>1024*1024)throw new IllegalStateException("Report exceeds 1 MiB read limit");return new String(bytes,StandardCharsets.UTF_8);}catch(Exception e){throw new IllegalStateException(e);}}
   JsonObject deleteReport(String project,String runId,String name){if(name.contains("/")||name.contains("\\")||name.contains(".."))throw new IllegalArgumentException("Invalid report name");IFile f=run(project,runId,false).getFolder("reports").getFile(name);if(!f.exists())throw new IllegalArgumentException("Report not found: "+name);try{f.delete(true,new NullProgressMonitor());}catch(Exception e){throw new IllegalStateException(e);}JsonObject r=new JsonObject();r.addProperty("deleted",true);r.addProperty("name",name);return r;}
   private void recoverAborted(){for(IProject p:ResourcesPlugin.getWorkspace().getRoot().getProjects())if(p.isOpen()){IFolder runs=runs(p.getName(),false);if(runs!=null&&runs.exists())try{for(IResource r:runs.members())if(r instanceof IFolder f){IFile mf=f.getFile("manifest.json");if(!mf.exists())continue;JsonObject m=read(mf);String state=StudioJson.string(m,"state","");if(state.equals("running")||state.equals("queued")){m.addProperty("state","aborted");m.addProperty("finished_at",StudioJson.now());m.addProperty("recovery_note","DBeaver restarted before the run finalized");write(mf,m);}}}catch(Exception ignored){}}}
   private static IProject project(String name){IProject p=ResourcesPlugin.getWorkspace().getRoot().getProject(name);if(!p.exists()||!p.isOpen())throw new IllegalArgumentException("Open project not found: "+name);return p;}
   private static IFolder runs(String project,boolean create){IProject p=project(project);IFolder root=p.getFolder(ROOT);IFolder runs=root.getFolder(RUNS);try{if(create){if(!root.exists())root.create(true,true,new NullProgressMonitor());if(!runs.exists())runs.create(true,true,new NullProgressMonitor());}}catch(Exception e){throw new IllegalStateException(e);}return runs;}
   private static IFolder run(String project,String id,boolean create){if(!id.matches("[A-Za-z0-9._-]{1,160}"))throw new IllegalArgumentException("Invalid run id");IFolder f=runs(project,create).getFolder(id);try{if(create&&!f.exists())f.create(true,true,new NullProgressMonitor());}catch(Exception e){throw new IllegalStateException(e);}return f;}
   private static IFolder child(IFolder parent,String name,boolean create){IFolder f=parent.getFolder(name);try{if(create&&!f.exists())f.create(true,true,new NullProgressMonitor());}catch(Exception e){throw new IllegalStateException(e);}return f;}
   private static void write(IFile file,JsonObject object){writeBytes(file,StudioJson.GSON.toJson(object).getBytes(StandardCharsets.UTF_8));}
   private static void writeBytes(IFile file,byte[] bytes){try(ByteArrayInputStream in=new ByteArrayInputStream(bytes)){if(file.exists())file.setContents(in,IResource.FORCE|IResource.KEEP_HISTORY,new NullProgressMonitor());else file.create(in,IResource.FORCE,new NullProgressMonitor());}catch(Exception e){throw new IllegalStateException(e);}}
   private static JsonObject read(IFile file){try(var in=file.getContents()){return StudioJson.parseObject(new String(in.readAllBytes(),StandardCharsets.UTF_8));}catch(Exception e){throw new IllegalStateException(e);}}
   private static long folderSize(IFolder folder){try{return Arrays.stream(folder.members()).mapToLong(r->r instanceof IFolder f?folderSize(f):r.getLocation().toFile().length()).sum();}catch(Exception e){return 0;}}
   private static void checkQuota(IFolder run){long size=folderSize(run);if(size>MAX_RUN_BYTES)throw new IllegalStateException("Run evidence exceeds 50 MiB quota");}
   private static String sha(byte[] bytes){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}catch(Exception e){throw new IllegalStateException(e);}}
   private static JsonObject count(int n){JsonObject r=new JsonObject();r.addProperty("removed_count",n);return r;}
}
